import type { Product } from './types';

/**
 * Sample product data used until a real Sanity project is connected
 * (see .env.local.example) or until the client adds real products
 * through the /studio admin panel. Lets the site go live on day one.
 */
export const fallbackProducts: Product[] = [
  {
    _id: 'sample-rose-gold-ring',
    name: 'Rose Gold Charm Ring',
    slug: 'rose-gold-charm-ring',
    category: 'rings',
    price: 1299,
    badge: 'New',
    rating: 5,
    reviews: 128,
    imageUrl: 'https://images.unsplash.com/photo-1705326455036-0fab8ecba04d?w=500&q=80',
    featured: true,
    inStock: true,
  },
  {
    _id: 'sample-pearl-necklace',
    name: 'Dainty Pearl Necklace',
    slug: 'dainty-pearl-necklace',
    category: 'necklaces',
    price: 1899,
    badge: 'Hot',
    rating: 5,
    reviews: 96,
    imageUrl: 'https://images.unsplash.com/photo-1595345705177-ffe090eb0784?w=500&q=80',
    featured: true,
    inStock: true,
  },
  {
    _id: 'sample-crystal-earrings',
    name: 'Crystal Drop Earrings',
    slug: 'crystal-drop-earrings',
    category: 'earrings',
    price: 999,
    rating: 4,
    reviews: 54,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500&q=80',
    featured: true,
    inStock: true,
  },
  {
    _id: 'sample-gold-bracelet',
    name: 'Delicate Gold Bracelet',
    slug: 'delicate-gold-bracelet',
    category: 'bracelets',
    price: 1499,
    oldPrice: 1999,
    badge: 'Sale',
    rating: 5,
    reviews: 142,
    imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=500&q=80',
    featured: true,
    inStock: true,
  },
  {
    _id: 'sample-solitaire-ring',
    name: 'Crystal Solitaire Ring',
    slug: 'crystal-solitaire-ring',
    category: 'rings',
    price: 1599,
    rating: 5,
    reviews: 87,
    imageUrl: 'https://images.unsplash.com/photo-1587593692659-38c32c496642?w=500&q=80',
    inStock: true,
  },
  {
    _id: 'sample-layered-necklace',
    name: 'Layered Gold Necklace',
    slug: 'layered-gold-necklace',
    category: 'necklaces',
    price: 2199,
    badge: 'New',
    rating: 5,
    reviews: 63,
    imageUrl: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=500&q=80',
    inStock: true,
  },
  {
    _id: 'sample-hoop-earrings',
    name: 'Mini Gold Hoop Earrings',
    slug: 'mini-gold-hoop-earrings',
    category: 'earrings',
    price: 799,
    rating: 4,
    reviews: 41,
    imageUrl: 'https://images.unsplash.com/photo-1535556116002-6281ff3e9f36?w=500&q=80',
    inStock: true,
  },
  {
    _id: 'sample-charm-anklet',
    name: 'Charm Anklet',
    slug: 'charm-anklet',
    category: 'anklets',
    price: 699,
    rating: 5,
    reviews: 72,
    imageUrl: 'https://images.unsplash.com/photo-1744722091259-ed1cf11ac97f?w=500&q=80',
    inStock: true,
  },
];
